/*
 * @(#)Test.java
 *
 * Project:		JHotdraw - a GUI framework for technical drawings
 *				http://www.jhotdraw.org
 *				http://jhotdraw.sourceforge.net
 * Copyright:	� by the original author(s) and all contributors
 * License:		Lesser GNU Public License (LGPL)
 *				http://www.opensource.org/licenses/lgpl-license.html
 */
package org.fmatjhotdraw.test.standard;

import junit.framework.TestSuite;
// JUnitDoclet begin import
// JUnitDoclet end import

/*
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/

// JUnitDoclet begin javadoc_class
/**
* TestSuite StandardSuite
*/
// JUnitDoclet end javadoc_class
public class StandardSuite
// JUnitDoclet begin extends_implements
// JUnitDoclet end extends_implements
{
	// JUnitDoclet begin class
	// JUnitDoclet end class

	public static TestSuite suite() {

		TestSuite suite;

		suite = new TestSuite("org.fmatjhotdraw.test.standard");

		suite.addTestSuite(org.fmatjhotdraw.test.standard.PeripheralLocatorTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.SingleFigureEnumeratorTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.NullDrawingViewTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.NullToolTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.HandleAndEnumeratorTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.InsertIntoDrawingVisitorTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.DeleteFromDrawingVisitorTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.SelectAllCommandTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.FigureAndEnumeratorTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.HandleEnumeratorTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.StandardFigureSelectionTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.FastBufferedUpdateStrategyTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.ToolButtonTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.ToggleGridCommandTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.StandardDrawingViewTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.StandardDrawingTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.SimpleUpdateStrategyTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.SelectionToolTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.SelectAreaTrackerTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.ReverseFigureEnumeratorTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.RelativeLocatorTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.PasteCommandTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.OffsetLocatorTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.NullHandleTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.LocatorConnectorTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.HandleTrackerTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.GridConstrainerTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.FigureEnumeratorTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.FigureChangeEventMulticasterTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.DuplicateCommandTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.DragTrackerTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.DeleteCommandTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.CutCommandTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.CreationToolTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.CopyCommandTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.ConnectionToolTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.ConnectionHandleTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.ChopBoxConnectorTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.ChangeConnectionStartHandleTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.ChangeConnectionEndHandleTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.ChangeAttributeCommandTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.BufferedUpdateStrategyTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.SendToBackCommandTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.BringToFrontCommandTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.LocatorHandleTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.BoxHandleKitTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.AlignCommandTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.standard.FigureChangeAdapterTest.class);

		// JUnitDoclet begin method suite()
		// JUnitDoclet end method suite()

		return suite;
	}

	/**
	* Method to execute the TestSuite from command line
	* using JUnit's textui.TestRunner .
	*/
	public static void main(String[] args) {
		// JUnitDoclet begin method testsuite.main
		junit.textui.TestRunner.run(suite());
		// JUnitDoclet end method testsuite.main
	}
}
