/*
 * @(#)Test.java
 *
 * Project:		JHotdraw - a GUI framework for technical drawings
 *				http://www.jhotdraw.org
 *				http://jhotdraw.sourceforge.net
 * Copyright:	� by the original author(s) and all contributors
 * License:		Lesser GNU Public License (LGPL)
 *				http://www.opensource.org/licenses/lgpl-license.html
 */
package org.fmatjhotdraw.test.util;

import junit.framework.TestSuite;
// JUnitDoclet begin import
// JUnitDoclet end import

/*
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/

// JUnitDoclet begin javadoc_class
/**
* TestSuite UtilSuite
*/
// JUnitDoclet end javadoc_class
public class UtilSuite
// JUnitDoclet begin extends_implements
// JUnitDoclet end extends_implements
{
	// JUnitDoclet begin class
	// JUnitDoclet end class

	public static TestSuite suite() {

		TestSuite suite;

		suite = new TestSuite("org.fmatjhotdraw.test.util");

		suite.addTestSuite(org.fmatjhotdraw.test.util.ReverseListEnumeratorTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.util.StandardVersionControlStrategyTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.util.VersionManagementTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.util.UndoableHandleTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.util.UndoRedoActivityTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.util.UndoableAdapterTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.util.UndoableToolTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.util.RedoCommandTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.util.UndoCommandTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.util.UndoableCommandTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.util.GraphLayoutTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.util.BoundsTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.util.StorageFormatManagerTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.util.SerializationStorageFormatTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.util.StandardStorageFormatTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.util.PaletteLayoutTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.util.PaletteIconTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.util.IconkitTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.util.GeomTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.util.FloatingTextFieldTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.util.FillerTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.util.CommandMenuTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.util.CommandChoiceTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.util.CommandButtonTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.util.StorableInputTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.util.StorableOutputTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.util.UndoManagerTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.util.ColorMapTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.util.ClipboardTest.class);

		// JUnitDoclet begin method suite()
		// JUnitDoclet end method suite()

		return suite;
	}

	/**
	* Method to execute the TestSuite from command line
	* using JUnit's textui.TestRunner .
	*/
	public static void main(String[] args) {
		// JUnitDoclet begin method testsuite.main
		junit.textui.TestRunner.run(suite());
		// JUnitDoclet end method testsuite.main
	}
}
