/*
 * @(#)FiguresSuite.java
 *
 * Project:     JHotdraw - a GUI framework for technical drawings
 *              http://www.jhotdraw.org
 *              http://jhotdraw.sourceforge.net
 * Copyright:   � by the original author(s) and all contributors
 * License:     Lesser GNU Public License (LGPL)
 *              http://www.opensource.org/licenses/lgpl-license.html
 */
package org.fmatjhotdraw.test.figures;

import junit.framework.TestSuite;
// JUnitDoclet begin import
// JUnitDoclet end import

/*
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/

// JUnitDoclet begin javadoc_class
/**
* TestSuite FiguresSuite
*/
// JUnitDoclet end javadoc_class
public class FiguresSuite
// JUnitDoclet begin extends_implements
// JUnitDoclet end extends_implements
{
	// JUnitDoclet begin class
	// JUnitDoclet end class

	public static TestSuite suite() {

		TestSuite suite;

		suite = new TestSuite("org.fmatjhotdraw.test.figures");

		suite.addTestSuite(org.fmatjhotdraw.test.figures.NullConnectorTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.figures.NullFigureTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.figures.UngroupCommandTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.figures.ShortestDistanceConnectorTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.figures.ScribbleToolTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.figures.RectangleFigureTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.figures.RoundRectangleFigureTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.figures.PolyLineHandleTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.figures.PolyLineConnectorTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.figures.NumberTextFigureTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.figures.LineFigureTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.figures.InsertImageCommandTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.figures.ImageFigureTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.figures.GroupFigureTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.figures.GroupCommandTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.figures.FontSizeHandleTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.figures.EllipseFigureTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.figures.ElbowHandleTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.figures.ElbowConnectionTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.figures.TextToolTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.figures.ConnectedTextToolTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.figures.ChopEllipseConnectorTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.figures.BorderToolTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.figures.BorderDecoratorTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.figures.ArrowTipTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.figures.FigureAttributesTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.figures.TextFigureTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.figures.PolyLineFigureTest.class);
		suite.addTestSuite(org.fmatjhotdraw.test.figures.LineConnectionTest.class);

		// JUnitDoclet begin method suite()
		// JUnitDoclet end method suite()

		return suite;
	}

	/**
	* Method to execute the TestSuite from command line
	* using JUnit's textui.TestRunner .
	*/
	public static void main(String[] args) {
		// JUnitDoclet begin method testsuite.main
		junit.textui.TestRunner.run(suite());
		// JUnitDoclet end method testsuite.main
	}
}
